/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {
      type: 'autogenerated', 
      dirName: 'wiki'
    }
  ],
  thinking: [
    {
      type: 'autogenerated',
      dirName: 'thinking'
    },
  ],
  reading: [
    {
      type: 'autogenerated',
      dirName: 'reading'
    },
  ],
  exercise: [
    {
      type: 'autogenerated',
      dirName: 'exercise'
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  // thinkSidebar: {  // 侧边栏
  //   '分类 A': ['doc1', 'doc2'],
  //   '分类 B': ['doc3', 'doc4'],
  // },
  // readSidebar: {  // 侧边栏
  //   '分类 C': ['doc7', 'doc8'],
  //   '分类 D': ['doc9', 'doc10'],
  // },
  
};
